src/main/java/de/belmega/pardernote/jsf/LoginBean.java
package de.belmega.pardernote.jsf;

import org.apache.commons.lang.StringUtils;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

@Named
@RequestScoped
public class LoginBean {

    public static final String ATTRIBUTE_USER = "username";

    private String username;
    private Object sessionUsername;

    public LoginBean() {
    }

    public String logout() {
        getHttpSession().invalidate();
        return "";
    }

    private HttpSession getHttpSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }

    public Boolean getLoggedIn() {
        if (sessionUsername == null) {
            HttpSession session = getHttpSession();
            sessionUsername = session.getAttribute(ATTRIBUTE_USER);
        }

        boolean sessionHasLoggedInUser = sessionUsername != null;
        return sessionHasLoggedInUser;
    }

    public void login() {
        if (StringUtils.isEmpty(username)) return;

        HttpSession session = getHttpSession();
        session.setAttribute(ATTRIBUTE_USER, username);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getGreeting() {
        String username = (String) getHttpSession().getAttribute(ATTRIBUTE_USER);
        return "Hallo, " + username + ".";
    }

    public String getGreetingGuest() {
        return "Hallo, Gast.";
    }
}

src/main/webapp/template/commonContent.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<body>
<ui:composition>

    <h1>This is default content</h1>

</ui:composition>
</body>
</html>

src/main/webapp/template/commonFooter.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
>
<body>
<ui:composition>

    <div><a href="https://bitbucket.org/tbelmega/pardernote">ParderNote 1.0</a></div>

</ui:composition>
</body>
</html>

src/main/webapp/template/commonHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
>
<body>
<ui:composition>
    <div id="title-bar">
        <h:form class="loggedInBar" rendered="#{loginBean.loggedIn}">
            <h:outputLabel class="lblGreeting" value="#{loginBean.greeting}"></h:outputLabel>
            <p>
                <h:commandLink class="linkLogout" action="#{loginBean.logout}">Abmelden</h:commandLink>
            </p>
        </h:form>
        <h:form class="loggedInBar" rendered="#{!loginBean.loggedIn}">
            <h:outputLabel class="lblGreeting" value="#{loginBean.greetingGuest}"></h:outputLabel>
            <p>
                <h:outputLabel value="Nutzername: "></h:outputLabel>
                <h:inputText class="loginInputText" value="#{loginBean.username}"></h:inputText>
                <h:commandLink class="linkLogin" action="#{loginBean.login}">Anmelden</h:commandLink>
            </p>
        </h:form>
    </div>
</ui:composition>
</body>
</html>

src/main/webapp/template/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>ParderNote</title>
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/resources/css/pardernote.css"/>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"/>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"/>

    <f:facet name="first">
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
    </f:facet>
</h:head>

<h:body>
    <div class="page">
        <div class="container-fluid">
            <f:view>
                <div id="header">
                    <ui:insert name="header">
                        <ui:include src="/template/commonHeader.xhtml"/>
                    </ui:insert>
                </div>
                <div id="content">
                    <ui:insert name="content">
                        <ui:include src="/template/commonContent.xhtml"/>
                    </ui:insert>
                </div>
                <div id="footer">
                    <ui:insert name="footer" >
                        <ui:include src="/template/commonFooter.xhtml" />
                    </ui:insert>
                </div>
            </f:view>
        </div>
    </div>
</h:body>
</html>