src/main/java/de/belmega/pardernote/dto/NoteDTO.java
package de.belmega.pardernote.dto;


import org.apache.commons.lang.StringUtils;

import java.util.Date;
import java.util.Optional;

public class NoteDTO {
    private final Long id;

    private String text;
    private Long creationTimestamp;
    private String title;
    private String author;
    private boolean done;
    private boolean archive;
    private Date todoUntil;
    private long priority;

    public NoteDTO(long id) {
        this.id = id;
    }

    public NoteDTO() {
        this.id = null;
    }

    public String getText() {
        return text;
    }

    public String getTitle() {
        if (StringUtils.isEmpty(this.title) && !StringUtils.isEmpty(this.text)) {
            // Show at most 30 characters of the note text
            if (this.text.length() <= 30) return this.text;
            else return this.text.substring(0, 30) + "...";
        } else return this.title;
    }

    public String getAuthor() {
        return author;
    }

    public Long getId() {
        return id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Long getCreationTimestamp() {
        return creationTimestamp;
    }

    public void setCreationTimestamp(Long creationTimestamp) {
        this.creationTimestamp = creationTimestamp;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public boolean isArchive() {
        return archive;
    }

    public void setArchive(boolean archive) {
        this.archive = archive;
    }

    public Date getTodoUntil() {
        return todoUntil;
    }

    public void setTodoUntil(Date todoUntil) {
        this.todoUntil = todoUntil;
    }

    public long getPriority() {
        return priority;
    }

    public void setPriority(long priority) {
        this.priority = priority;
    }
}

src/main/java/de/belmega/pardernote/persistence/entities/NoteEntity.java
package de.belmega.pardernote.persistence.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class NoteEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
    private String text;
    private long creationTimestamp;
    private String author;
    private String title;
    private Long todoUntil;
    private long priority = 0;
    private boolean done = false;
    private boolean archive = false;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return text;
    }

    public void setCreationTimestamp(long creationTimestamp) {
        this.creationTimestamp = creationTimestamp;
    }

    public long getCreationTimestamp() {
        return creationTimestamp;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getTodoUntil() {
        return todoUntil;
    }

    public void setTodoUntil(Long todoUntil) {
        this.todoUntil = todoUntil;
    }

    public long getPriority() {
        return priority;
    }

    public void setPriority(long priority) {
        this.priority = priority;
    }

    public boolean isDone() {
        return done;
    }

    public void setDone(boolean done) {
        this.done = done;
    }

    public boolean isArchive() {
        return archive;
    }

    public void setArchive(boolean archive) {
        this.archive = archive;
    }

    @Override
    public String toString() {
        return "NoteEntity{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", creationTimestamp=" + creationTimestamp +
                ", author='" + author + '\'' +
                ", title='" + title + '\'' +
                ", todoUntil=" + todoUntil +
                ", priority=" + priority +
                ", done=" + done +
                ", archive=" + archive +
                '}';
    }
}

src/main/java/de/belmega/pardernote/jsf/LoginBean.java
package de.belmega.pardernote.jsf;

import org.apache.commons.lang.StringUtils;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

@Named
@RequestScoped
public class LoginBean {

    public static final String ATTRIBUTE_USER = "username";

    private String username;
    private Object sessionUsername;

    public LoginBean() {
    }

    public String logout() {
        getHttpSession().invalidate();
        return "";
    }

    private HttpSession getHttpSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }

    public Boolean getLoggedIn() {
        if (sessionUsername == null) {
            HttpSession session = getHttpSession();
            sessionUsername = session.getAttribute(ATTRIBUTE_USER);
        }

        boolean sessionHasLoggedInUser = sessionUsername != null;
        return sessionHasLoggedInUser;
    }

    public void login() {
        if (StringUtils.isEmpty(username)) return;

        HttpSession session = getHttpSession();
        session.setAttribute(ATTRIBUTE_USER, username);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getGreeting() {
        String username = (String) getHttpSession().getAttribute(ATTRIBUTE_USER);
        return "Hallo, " + username + ".";
    }

    public String getGreetingGuest() {
        return "Hallo, Gast.";
    }
}

src/main/java/de/belmega/pardernote/jsf/NoteCreateBean.java
package de.belmega.pardernote.jsf;

import de.belmega.pardernote.dto.NoteDTO;
import de.belmega.pardernote.service.NoteService;
import org.apache.commons.lang.StringUtils;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

import static de.belmega.pardernote.jsf.LoginBean.ATTRIBUTE_USER;

@Named
@RequestScoped
public class NoteCreateBean {

    public static final String NOTELIST_PAGE = "notelist?faces-redirect=true";
    public static final String INDEX_PAGE = "index?faces-redirect=true";

    @Inject
    NoteService noteService;

    private NoteDTO noteDTO;

    @PostConstruct
    public void init() {
        this.noteDTO = new NoteDTO();
    }

    public String clear() {
        this.noteDTO = new NoteDTO();
        return "";
    }

    public String save() {
        saveNewNote();
        return NOTELIST_PAGE;
    }

    private void saveNewNote() {
        String author = (String) getHttpSession().getAttribute(ATTRIBUTE_USER);
        if (StringUtils.isEmpty(author))
            author = "Gast";

        this.noteDTO.setAuthor(author);
        this.noteDTO.setCreationTimestamp(System.currentTimeMillis());
        noteService.storeNewNote(this.noteDTO);
    }


    private HttpSession getHttpSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }

    public String saveAndNew() {
        saveNewNote();
        return INDEX_PAGE;
    }

    public NoteDTO getNote() {
        return noteDTO;
    }

    public void setNote(NoteDTO note) {
        this.noteDTO = note;
    }
}

src/main/java/de/belmega/pardernote/jsf/NoteDetailsBean.java
package de.belmega.pardernote.jsf;

import de.belmega.pardernote.dto.NoteDTO;
import de.belmega.pardernote.service.NoteService;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Optional;

@Named
@ConversationScoped
public class NoteDetailsBean implements Serializable {

    private String noteId;

    private NoteDTO note;

    @Inject
    NoteService noteService;

    @Inject
    private Conversation conversation;

    public void loadNote() {
        if (this.note != null) return;

        conversation.begin();
        if (noteId == null) throw new IllegalArgumentException("Cannot load Note without ID.");

        Optional<NoteDTO> note = noteService.findById(noteId);
        if (!note.isPresent()) throw new IllegalArgumentException("Note with this ID does not exist.");

        this.note = note.get();
        System.out.println("Loaded note:" + this.note);
    }

    public String save() {
        System.out.println(this.note);
        noteService.updateNote(this.note);
        return back();
    }

    public String back() {
        conversation.end();
        return "notelist.xhtml?faces-redirect=true";
    }

    public String getNoteId() {
        return noteId;
    }

    public void setNoteId(String noteId) {
        this.noteId = noteId;
    }

    public NoteDTO getNote() {
        return note;
    }

    public void setNote(NoteDTO note) {
        this.note = note;
    }

    public String archive() {
        note.setArchive(true);
        return save();
    }
}

src/main/java/de/belmega/pardernote/jsf/NoteListBean.java
package de.belmega.pardernote.jsf;

import de.belmega.pardernote.dto.NoteDTO;
import de.belmega.pardernote.service.NoteService;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

@Named
@RequestScoped
public class NoteListBean {

    @Inject
    NoteService noteService;
    private int orderByTitleAscending;

    private List<NoteDTO> allNotes;

    public List<NoteDTO> getNotes() {
        if (allNotes == null) {
            allNotes = noteService.getAllNotes();
        }
        return allNotes;
    }
}

src/main/webapp/index.xhtml
<ui:composition template="template/template.xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

    <ui:define name="content">
        <h:form>
            <div>
                <h2>Notiz anlegen</h2>
                <h:inputTextarea value="#{noteCreateBean.note.text}" cols="80" rows="10"/>
            </div>
            <h:commandLink class="toggle" onclick="$('#optionals').toggleClass('hidden'); return false;">
                Optionale Felder einblenden</h:commandLink>
            <div id="optionals" class="hidden">
                <table>
                    <tr>
                        <td>
                            <h:outputText value="Titel"></h:outputText>
                        </td>
                        <td>
                            <h:inputText id="Titel" value="#{noteCreateBean.note.title}"></h:inputText>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h:outputText value="Priorität"></h:outputText>
                        </td>
                        <td>
                            <h:inputText id="Priority" value="#{noteCreateBean.note.priority}"></h:inputText>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h:outputText value="Zu erledigen bis"></h:outputText>
                        </td>
                        <td>
                            <h:inputText id="TodoUntil" value="#{noteCreateBean.note.todoUntil}" a:placeholder="dd.mm.yyyy">
                                <f:convertDateTime pattern="dd.mm.yyyy"></f:convertDateTime>
                            </h:inputText>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h:outputText value="Erledigt"></h:outputText>
                        </td>
                        <td>
                            <h:selectBooleanCheckbox id="Done" value="#{noteCreateBean.note.done}"></h:selectBooleanCheckbox>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="buttons-hbox">
                <h:commandButton value="Speichern und zur Liste" action="#{noteCreateBean.save()}"/>
                <h:commandButton value="Speichern und weitere Notiz" action="#{noteCreateBean.saveAndNew()}"/>
                <h:commandButton value="Verwerfen" action="#{noteCreateBean.clear()}"/>
                <h:commandButton value="Zurück" action="notelist.xhtml?faces-redirect=true"/>
            </div>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/notedetails.xhtml
<ui:composition template="template/template.xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:a="http://xmlns.jcp.org/jsf/passthrough">

    <f:metadata>
        <!-- When page is loaded, get ID from URL and store it in the bean.
         Then call loadNote, to let the bean load the noteDTO. -->
        <f:viewParam name="noteId" value="#{noteDetailsBean.noteId}"/>
        <f:event type="preRenderComponent" listener="#{noteDetailsBean.loadNote}"/>
    </f:metadata>

    <ui:define name="content">
        <h:form>
            <h2>Notizdetails</h2>
            <table>
                <tr>
                    <td>
                        Titel:
                    </td>
                    <td>
                        <h:inputText value="#{noteDetailsBean.note.title}"></h:inputText>
                    </td>
                </tr>
                <tr>
                    <td>
                        Text:
                    </td>
                    <td>
                        <h:inputTextarea value="#{noteDetailsBean.note.text}" cols="80" rows="10"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Autor:
                    </td>
                    <td>
                        #{noteDetailsBean.note.author}
                    </td>
                </tr>
                <tr>
                    <td>
                        Erstellt:
                    </td>
                    <td>
                        <h:outputText value="#{noteDetailsBean.note.creationTimestamp}">
                            <f:convertDateTime pattern="dd.MM.yyyy HH:mm" locale="de_DE"/>
                        </h:outputText>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h:outputText value="Priorität"></h:outputText>
                    </td>
                    <td>
                        <h:inputText id="Priority" value="#{noteDetailsBean.note.priority}"></h:inputText>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h:outputText value="Zu erledigen bis"></h:outputText>
                    </td>
                    <td>
                        <h:inputText id="TodoUntil" value="#{noteDetailsBean.note.todoUntil}" a:placeholder="dd.mm.yyyy">
                            <f:convertDateTime pattern="dd.mm.yyyy"></f:convertDateTime>
                        </h:inputText>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h:outputText value="Erledigt"></h:outputText>
                    </td>
                    <td>
                        <h:selectBooleanCheckbox id="Done" value="#{noteDetailsBean.note.done}"></h:selectBooleanCheckbox>
                    </td>
                </tr>
            </table>

            <div class="buttons-hbox">
                <h:commandButton value="Speichern" action="#{noteDetailsBean.save()}">
                    <f:param name="noteId" value="#{note.id()}"/>
                </h:commandButton>
                <h:commandButton value="Löschen" action="#{noteDetailsBean.archive()}"
                                 onclick="return confirm('Diese Notiz wirklich löschen?')">
                    <f:param name="noteId" value="#{note.id()}"/>
                </h:commandButton>
                <h:commandButton value="Zurück" action="#{noteDetailsBean.back()}">
                    <f:param name="noteId" value="#{note.id()}"/>
                </h:commandButton>
            </div>
        </h:form>

    </ui:define>

</ui:composition>

src/main/webapp/notelist.xhtml
<ui:composition template="template/template.xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="content">
        <h2>Alle Notizen</h2>
        <h:dataTable value="#{noteListBean.notes}" var="note" class="data-table"
                     columnClasses="title-column, date-column, author-column">
            <h:column>
                <f:facet name="header">
                    Titel
                </f:facet>

                <h:link value="#{note.title}" outcome="notedetails.xhtml">
                    <f:param name="noteId" value="#{note.id()}"/>
                </h:link>
            </h:column>
            <h:column>
                <f:facet name="header">Angelegt
                </f:facet>
                <h:outputText value="#{note.creationTimestamp}">
                    <f:convertDateTime pattern="dd.MM.yyyy HH:mm"/>
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Autor</f:facet>
                #{note.author}
            </h:column>
            <h:column>
                <f:facet name="header">Priorität</f:facet>
                #{note.priority}
            </h:column>
            <h:column>
                <f:facet name="header">Erledigen bis</f:facet>
                <h:outputText value="#{note.todoUntil}">
                    <f:convertDateTime pattern="dd.MM.yyyy"/>
                </h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Erledigt</f:facet>
                <h:selectBooleanCheckbox value="#{note.done}" disabled="true"></h:selectBooleanCheckbox>
            </h:column>
        </h:dataTable>

        <div class="buttons-hbox">
            <h:form>
                <h:commandButton action="index.xhtml?faces-redirect=true" value="Neue Notiz"></h:commandButton>
            </h:form>
        </div>

    </ui:define>

</ui:composition>